
development:
  adapter: postgresql
  database: guestbook
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: guestbook_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: guestbook_pro
  pool: 5
  timeout: 5000
